export const WANDERERS_SCREEN = {
  title: 'Странники',
  subtitle: 'Выбери тех, с кем отправишься в путь',
  subtitleDesktop: 'Выбери тех, с кем отправишься в путь',
  subtitleFavorites: 'Избранные анкеты',
  subtitleSkipped: 'Скрытые анкеты',
  empty: 'Пока нет новых анкет в ленте',
  emptyHint: 'Загляните позже или посмотрите избранные и скрытые.',
  emptyFavorites: 'Избранных пока нет',
  emptyFavoritesHint: 'Добавляйте понравившиеся анкеты из ленты.',
  emptySkipped: 'Скрытых анкет пока нет',
  emptySkippedHint: 'Скрытые анкеты из основной ленты появятся здесь.',
  emptyFiltered: 'Нет анкет по выбранным фильтрам',
  emptyFilteredHint: 'Снимите часть фильтров или сбросьте их — фильтры дополняют друг друга.',
  loadError: 'Не удалось загрузить ленту',
  likeAction: 'В избранные',
  passAction: 'Скрыть',
  chatAction: 'Написать',
  removeFavoriteAction: 'Удалить из избранных',
  removeHiddenAction: 'Удалить из скрытых',
  unblockAction: 'Разблокировать',
  moreActionsLabel: 'Ещё',
  moveToFavoritesAction: 'В избранные',
  moveToSkippedAction: 'В скрытые',
  undoAction: 'Назад',
  swipeHint: 'Потяните карточку влево или вправо',
  swipeHintPass: 'Скрыть',
  swipeHintLike: 'В избранные',
  finishedTitle: 'Анкеты закончились',
  finishedSubtitle: 'Вы просмотрели всех странников',
  finishedHint: 'Можно начать сначала или вернуться позже — появятся новые игроки',
  finishedFavoritesTitle: 'Избранные просмотрены',
  finishedFavoritesHint: 'Можно пройти список снова или вернуться в ленту.',
  finishedSkippedTitle: 'Скрытые просмотрены',
  finishedSkippedHint: 'Можно пройти список снова или вернуть кого-то в избранные.',
  restartLabel: 'Смотреть снова',
  bucketFeed: 'Лента',
  bucketFavorites: 'Избранные',
  bucketSkipped: 'Скрытые',
} as const;
